### ISSUE TITLE
Great tool, thanks

### ISSUE THREAD

**Issue by mholt** [marhaupe/json2struct#13]
Didn't choke on my 1 GB JSON file, and only took about a minute. Saved me a ton of time.

**Comment by marhaupe** [comment]
Thanks! You're a legend so that means alot coming from you, I really appreciate it!

**Comment by mholt** [comment]
Ha, well, you wrote a tool that mine couldn't handle, so...

**Comment by atc0005** [comment]
@marhaupe Seconding! This tool really came in handy when setting up a new project. Thanks!
